BEGIN;

-- 1. Drop all tables
DROP TABLE IF EXISTS system_notifications CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS client_reports CASCADE;
DROP TABLE IF EXISTS trainer_reviews CASCADE;
DROP TABLE IF EXISTS training_reviews CASCADE;
DROP TABLE IF EXISTS training_exercises CASCADE;
DROP TABLE IF EXISTS assigned_trainings CASCADE;
DROP TABLE IF EXISTS live_trainings CASCADE;
DROP TABLE IF EXISTS trainings CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS cooperations CASCADE;
DROP TABLE IF EXISTS health_records CASCADE;
DROP TABLE IF EXISTS client_equipment CASCADE;
DROP TABLE IF EXISTS exercise_equipment CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS pricing_tiers CASCADE;
DROP TABLE IF EXISTS credentials CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS trainers CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. Drop all custom ENUM types
DROP TYPE IF EXISTS equipment_type CASCADE;
DROP TYPE IF EXISTS notification_type CASCADE;
DROP TYPE IF EXISTS report_status CASCADE;
DROP TYPE IF EXISTS training_status CASCADE;
DROP TYPE IF EXISTS training_type CASCADE;
DROP TYPE IF EXISTS cooperation_status CASCADE;
DROP TYPE IF EXISTS credential_type CASCADE;
DROP TYPE IF EXISTS training_location CASCADE;
DROP TYPE IF EXISTS registration_status CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;

DROP EXTENSION IF EXISTS "pgcrypto";

COMMIT;